name: Super-Linter

on: push

jobs:
  super-line:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      -name: Checkount code
      uses: actions/checkout@v2
      
      -name: Run Super-Linter
      uses: github/super-linter@v3
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
